AddressLine1: 4676 Admiralty Way 
Country: United States
Description: A unit of the University of Southern California’s highly ranked Viterbi School of Engineering
ID: 10237
Latitude: 33.9801
Longitude: -118.4400
State: CA
Zipcode: '90292'

