Country: United States
Description: CancerComputer's multi-purpose cluster located at UEL in Minneapolis
ID: 10237
Latitude: 44.970
LongName: CancerComputer-Minneapolis-UEL
Longitude: -93.203
State: MN
Zipcode: 55114
